### ISSUE TITLE
waitForSelector timeout always exceeded

### ISSUE THREAD

**Issue by hamed-musallam** [cheminfo/nmrium#1170]
@targos 

when test on firefox, The waitForSelector timeout always exceeded, even after I change the default time out from 3000 to 6000 Although it works on chrome with default timeout without a problem.

https://github.com/cheminfo/nmrium/runs/3076685601

**Comment by hamed-musallam** [comment]
@targos 

What do you think about this problem?

**Comment by targos** [comment]
@hamed-musallam the default timeout is 30'000, not 3'000, so your change is acually reducing it a lot, instead of increasing it.
If it only happens in Firefox, it's possible that there is a real issue is in the application (and not in the test).

**Comment by targos** [comment]
I restored the default timeout in https://github.com/cheminfo/nmrium/commit/0290d7cd910936b94daee0e2826903169164f76d
And I also pushed https://github.com/cheminfo/nmrium/commit/e560c0834a0ba49f69245b63da298573aed8fd2c. This makes sure the test files run in sequence instead of parallel, so it doesn't overload the test machines.

**Comment by targos** [comment]
If the problem persists on Firefox, I think you should try to reproduce the test steps with that browser.

**Comment by targos** [comment]
I think there's a real problem either with the test or the application. In webkit (Safari), it doesn't timeout but an assertion fails: https://github.com/cheminfo/nmrium/runs/3084904258

**Comment by hamed-musallam** [comment]
@targos 
yes, I run the test on Firefox on my local machine and its relay works after you put the option to run the tests in sequence instead of parallel, but I still have a problem In WebKit (Safari) so i tried the same test manually and use " npx playwright wk http://localhost:3000 " but the browser/displayer crash once i delete the range.

I have Windows Machine so I can not test on Safari to trace what I happening.

**Comment by targos** [comment]
You can open the developer tools in the WebKit browser opened by `npx playwright wk` (it's somewhere in the menu). I'm not able to reproduce a crash on my mac.

There's at least one issue in Safari, though: the peak labels all appear in the top-left corner of the viewport:

![image](https://user-images.githubusercontent.com/2352663/125946880-095a8e19-454d-4572-8a29-fe9795d33063.png)

**Comment by targos** [comment]
After https://github.com/cheminfo/nmrium/commit/59a1a6c4c5744ba20f342c48ec3b8381bf993680, there is no need for `waitForSelector` anymore.
